ens_jobeet:
    resource: "@EnsJobeetBundle/Resources/config/routing.yml"
    prefix:   /

EnsJobeetBundle_ens_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job
